#!/bin/bash

# Script: Ops 301 Class 02 Ops Challenge Solution
# Author: Jo Flow
# Date of latest revision: 8/30/2022 
# Purpose: Append; Date and Time

# Main


# Declare Variable
# guide for various commands to append date/time
    #https://www.cyberciti.biz/faq/unix-linux-appleosx-bsd-shell-appending-date-to-filename/ 

currentdate = $(date + %m_%d_%Y)
timenow=(date +)

cp /var/log/syslog 

echo 